project/django_pjt5/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/follow/',views.follow, name='follow'),
    path('delete/', views.delete, name='delete'),
    path('profile/<int:user_pk>', views.profile, name='profile'),
]

project/django_pjt5/django_pjt5/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('', views.index),
]

project/django_pjt5/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/like/', views.like, name='like'),
    path('recommend/', views.recommend, name='recommend'),
    path('genre/<int:genre_pk>', views.genre, name='genre'),
]

project/django_pjt5/accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    followers = models.ManyToManyField(
            settings.AUTH_USER_MODEL,
            related_name='followings'
        )

project/django_pjt5/movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length = 30)

class Movie(models.Model):
    title = models.CharField(max_length = 100)
    original_title = models.CharField(max_length = 100)
    release_date = models.DateField()
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    adult = models.BooleanField()
    overview = models.TextField()
    original_language = models.CharField(max_length = 30)
    poster_path = models.CharField(max_length = 200)
    backdrop_path = models.CharField(max_length = 200)
    genres = models.ManyToManyField(Genre, related_name='movies')
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies')

project/django_pjt5/accounts/forms.py
# from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['username']

project/django_pjt5/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.paginator import Paginator
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login, logout as auth_logout
from movies.models import Movie


from .forms import CustomUserCreationForm

User = get_user_model()

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:index')
    else:
        form = UserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('movies:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('movies:index')

@login_required
def follow(request, username):
    User = get_user_model()
    user = get_object_or_404(User, username=username)
    if user != request.user:
        if user.followers.filter(username=request.user.username).exists():
            user.followers.remove(request.user)
        else:
            user.followers.add(request.user)
    return redirect('accounts:profile', username)

@login_required
def delete(request):
    request.user.delete()
    messages.info(request, '회원탈퇴 되었습니다.')
    return redirect('movies:index')

@login_required
def profile(request, user_pk):
    user = get_object_or_404(User, pk=user_pk)
    if request.user == user:
        movies = Movie.objects.filter(like_users=user_pk)

        paginator = Paginator(movies, 12)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
    context = {
        'movies': movies,
        'page_obj':page_obj,
    }
    return render(request, 'accounts/profile.html', context)

project/django_pjt5/movies/views.py
from datetime import datetime, date
import random

from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import JsonResponse

from .models import Movie, Genre

# Create your views here.
def index(request):
    movies = Movie.objects.all()
    paginator = Paginator(movies, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'movies': movies,
        'page_obj': page_obj,
    }
    return render(request, 'movies/index.html', context)

@login_required
def like(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if movie.like_users.filter(id=request.user.pk).exists():
        movie.like_users.remove(request.user)
        liked=False
    else:
        movie.like_users.add(request.user)
        liked=True
    context = {
        'liked': liked,
        'count': movie.like_users.count(),
    }
    return JsonResponse(context)


@login_required
def recommend(request):
    day = datetime.today().day
    day=str(day)
    if len(day)==1:
        day='0'+day
    movies = Movie.objects.filter(release_date__endswith=day)
    if len(movies) >= 10:
        movies = random.sample(list(movies), 10)
    context = {
        'movies': movies,
        'day':day,
    }
    return render(request, 'movies/recommend.html', context)

def genre(request, genre_pk):

    movies = Movie.objects.filter(genres=genre_pk)
    genre = Genre.objects.get(pk=genre_pk)

    paginator = Paginator(movies, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'movies': movies,
        'page_obj': page_obj,
        'genre':genre.name
    }
    return render(request, 'movies/genre.html', context)

project/django_pjt5/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
  <h2>LOGIN</h2>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button>Submit</button>
  </form>
  <a href="{% url 'movies:index' %}">INDEX</a>
{% endblock %}

project/django_pjt5/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load bootstrap_pagination %}
{% block content %}
<h1>내가 좋아하는 영화</h1>
<hr>
<div class="container">
  <div class="row">
    {% for movie in page_obj %}
      <div class="col-4">
        <div class="card" style="width: 18rem;">
          <img src="https://image.tmdb.org/t/p/original/{{ movie.poster_path }}" class="card-img-top" alt="movie poster">
          <div class="card-body">
            <h5 class="card-title">{{ movie.title }}</h5>
            <p>장르: {% for genre in  movie.genres.all %} <a href="{% url 'movies:genre' genre.pk %}"><span class="badge badge-secondary">{{ genre.name }}</span></a> {% endfor %}</p>
            <p>평점: <span class="badge badge-info">{{ movie.vote_average }}</span></p>
            <p>개봉일 : {{ movie.release_date }}</p>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal-{{ movie.id }}">
              줄거리
            </button>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
    <!-- Modal -->
    {% for movie in movies %}
    <div class="modal fade" id="exampleModal-{{ movie.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">{{ movie.title }}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            {{ movie.overview }}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <a href='https://movie.naver.com/movie/search/result.nhn?query={{ movie.title }}&section=all&ie=utf8' class="btn btn-primary">검색</a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
<div class="text-center justify-content-center d-flex">
{% bootstrap_paginate page_obj range=10 %}
</div>
{% endblock %}

project/django_pjt5/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
  <h2>SIGNUP</h2>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button>Submit</button>
  </form>
  <a href="{% url 'movies:index' %}">INDEX</a>
{% endblock %}

project/django_pjt5/movies/templates/movies/genre.html
{% extends 'base.html' %}
{% load bootstrap_pagination %}

{% block content %}
<h1>{{ genre }} 장르 영화</h1>
<hr>
<div class="container">
  <div class="row">
    {% for movie in page_obj %}
      <div class="col-4">
        <div class="card" style="width: 18rem;">
          <img src="https://image.tmdb.org/t/p/original/{{ movie.poster_path }}" class="card-img-top" alt="movie poster">
          <div class="card-body">
            <h5 class="card-title">{{ movie.title }}</h5>
            <p>장르: {% for genre in  movie.genres.all %} <a href="{% url 'movies:genre' genre.pk %}"><span class="badge badge-secondary">{{ genre.name }}</span></a> {% endfor %}</p>
            <p>평점: <span class="badge badge-info">{{ movie.vote_average }}</span></p>
            <p>개봉일 : {{ movie.release_date }}</p>
            {% with movie_like_users=movie.like_users.all %}
                {% if request.user in movie_like_users %}
                  <i class="fas fa-heart fa-lg animated delay-1s like-button" data-id="{{ movie.id }}" style="color: crimson;"></i>
                {% else %}
                  <i class="fas fa-heart fa-lg animated infinite bounce delay-1s like-button" data-id="{{ movie.id }}" style="color: gray;"></i>
                {% endif %}
                <p class="d-inline like-count-{{ movie.id }}">{{ movie_like_users|length }}명이 좋아합니다.</p>
            {% endwith %}
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal-{{ movie.id }}">
              줄거리
            </button>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
    <!-- Modal -->
    {% for movie in movies %}
    <div class="modal fade" id="exampleModal-{{ movie.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">{{ movie.title }}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            {{ movie.overview }}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <a href='https://movie.naver.com/movie/search/result.nhn?query={{ movie.title }}&section=all&ie=utf8' class="btn btn-primary">검색</a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
<div class="text-center justify-content-center d-flex">
{% bootstrap_paginate page_obj range=10 %}
</div>
  <script>
    const likeBtns = document.querySelectorAll('.like-button')

    likeBtns.forEach(likeBtn => {
      likeBtn.addEventListener('click', function(event){
        const movieId = event.target.dataset.id
        axios.get(`/movies/${movieId}/like`)
          .then(response => {
            console.log('success')
            if (response.data.count) {
              document.querySelector(`.like-count-${movieId}`).innerText = response.data.count+'명이 좋아합니다.'
              if (response.data.liked) {
                event.target.style.color = 'crimson'
              } else {
                event.target.style.color = 'gray'
              }
            } else {
              confirm('로그인해주세요')
            }
          })
      })
    })
  </script>
{% endblock %}

project/django_pjt5/movies/templates/movies/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap_pagination %}
{% load bootstrap4 %}

{% block title %}영화 목록{% endblock %}
{% block content %}
<h1>Movies</h1>
<a class="btn btn-primary d-inline justify-content-end" href="{% url 'movies:recommend' %}">오늘 날짜에 개봉한 영화 추천</a>
<hr>
<div class="container">
  <div class="row">
    {% for movie in page_obj %}
      <div class="col-4">
        <div class="card" style="width: 18rem;">
          <img src="https://image.tmdb.org/t/p/original/{{ movie.poster_path }}" class="card-img-top" alt="movie poster">
          <div class="card-body">
            <h5 class="card-title">{{ movie.title }}</h5>
            <p>장르: {% for genre in  movie.genres.all %} <a href="{% url 'movies:genre' genre.pk %}"><span class="badge badge-secondary">{{ genre.name }}</span></a> {% endfor %}</p>
            <p>평점: <span class="badge badge-info">{{ movie.vote_average }}</span></p>
            <p>개봉일 : {{ movie.release_date }}</p>
            {% with movie_like_users=movie.like_users.all %}
                {% if request.user in movie_like_users %}
                  <i class="fas fa-heart fa-lg animated delay-1s like-button" data-id="{{ movie.id }}" style="color: crimson;"></i>
                {% else %}
                  <i class="fas fa-heart fa-lg animated infinite bounce delay-1s like-button" data-id="{{ movie.id }}" style="color: gray;"></i>
                {% endif %}
                <p class="d-inline like-count-{{ movie.id }}">{{ movie_like_users|length }}명이 좋아합니다.</p>
            {% endwith %}
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal-{{ movie.id }}">
              줄거리
            </button>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
    <!-- Modal -->
    {% for movie in movies %}
    <div class="modal fade" id="exampleModal-{{ movie.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">{{ movie.title }}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            {{ movie.overview }}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <a href='https://movie.naver.com/movie/search/result.nhn?query={{ movie.title }}&section=all&ie=utf8' class="btn btn-primary">검색</a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}

<br>
<br>
<div class="text-center justify-content-center d-flex">
{% bootstrap_paginate page_obj range=10 %}
</div>

  <script>
    const likeBtns = document.querySelectorAll('.like-button')

    likeBtns.forEach(likeBtn => {
      likeBtn.addEventListener('click', function(event){
        const movieId = event.target.dataset.id
        axios.get(`/movies/${movieId}/like`)
          .then(response => {
            console.log('success')
            if (response.data.count > -1) {
              document.querySelector(`.like-count-${movieId}`).innerText = response.data.count+'명이 좋아합니다.'
              if (response.data.liked) {
                event.target.style.color = 'crimson'
              } else {
                event.target.style.color = 'gray'
              }
            } else {
              confirm('로그인해주세요')
            }
          })
      })
    })
  </script>
{% endblock %}

project/django_pjt5/movies/templates/movies/recommend.html
{% extends 'base.html' %}

{% block content %}
<h1>오늘의 추천 영화 - {{ day }} 일에 개봉한 영화</h1>
<hr>
<div class="container">
  <div class="row">
    {% for movie in movies %}
      <div class="col-4">
        <div class="card" style="width: 18rem;">
          <img src="https://image.tmdb.org/t/p/original/{{ movie.poster_path }}" class="card-img-top" alt="movie poster">
          <div class="card-body">
            <h5 class="card-title">{{ movie.title }}</h5>
            <p>장르: {% for genre in  movie.genres.all %} <a href="{% url 'movies:genre' genre.pk %}"><span class="badge badge-secondary">{{ genre.name }}</span></a> {% endfor %}</p>
            <p>평점: <span class="badge badge-info">{{ movie.vote_average }}</span></p>
            <p>개봉일 : {{ movie.release_date }}</p>
            {% with movie_like_users=movie.like_users.all %}
                {% if request.user in movie_like_users %}
                  <i class="fas fa-heart fa-lg animated delay-1s like-button" data-id="{{ movie.id }}" style="color: crimson;"></i>
                {% else %}
                  <i class="fas fa-heart fa-lg animated infinite bounce delay-1s like-button" data-id="{{ movie.id }}" style="color: gray;"></i>
                {% endif %}
                <p class="d-inline like-count-{{ movie.id }}">{{ movie_like_users|length }}명이 좋아합니다.</p>
            {% endwith %}
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal-{{ movie.id }}">
              줄거리
            </button>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
    <!-- Modal -->
    {% for movie in movies %}
    <div class="modal fade" id="exampleModal-{{ movie.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">{{ movie.title }}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            {{ movie.overview }}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <a href='https://movie.naver.com/movie/search/result.nhn?query={{ movie.title }}&section=all&ie=utf8' class="btn btn-primary">검색</a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}

  <script>
    const likeBtns = document.querySelectorAll('.like-button')

    likeBtns.forEach(likeBtn => {
      likeBtn.addEventListener('click', function(event){
        const movieId = event.target.dataset.id
        axios.get(`/movies/${movieId}/like`)
          .then(response => {
            console.log('success')
            if (response.data.count > -1) {
              document.querySelector(`.like-count-${movieId}`).innerText = response.data.count+'명이 좋아합니다.'
              if (response.data.liked) {
                event.target.style.color = 'crimson'
              } else {
                event.target.style.color = 'gray'
              }
            } else {
              confirm('로그인해주세요')
            }
          })
      })
    })
  </script>

{% endblock %}