project/django_pjt4/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/',views.profile, name='profile'),
    path('<str:username>/follow/',views.follow, name='follow'),
    path('delete/', views.delete, name='delete'),
]

project/django_pjt4/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.movie_index, name='movie_index'),
    path('<int:movie_pk>/', views.reviews_index, name='reviews_index'),
    path('<int:movie_pk>/<int:review_pk>', views.review_detail, name='review_detail'),
    path('<int:movie_pk>/create/', views.create, name='create'),
    path('<int:movie_pk>/<int:review_pk>/update/', views.update, name='update'),
    path('<int:movie_pk>/<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:movie_pk>/<int:review_pk>/c_comment/', views.c_comment, name='c_comment'),
    path('<int:movie_pk>/<int:review_pk>/<int:comment_pk>/d_comment/', views.d_comment, name='d_comment'),
    path('<int:movie_pk>/<int:review_pk>/like/', views.like, name='like'),
]

project/django_pjt4/django_pjt4/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views

app_name = 'accounts'

urlpatterns = [
    path('', views.movie_index),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

project/django_pjt4/articles/models.py
from django.db import models
from django.conf import settings

class Movie(models.Model):
    movie_title = models.CharField(max_length = 100)
    movie_poster = models.TextField()

class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    title = models.CharField(max_length = 100)
    movie = models.ForeignKey(Movie, related_name='reviews', on_delete = models.CASCADE)
    rank = models.IntegerField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    hitcount = models.IntegerField()
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL,
                            related_name='like_reviews')

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    review = models.ForeignKey(Review,related_name='comments', on_delete = models.CASCADE)
    content = models.CharField(max_length = 200)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

project/django_pjt4/articles/forms.py
from django import forms
from .models import Movie, Review, Comment

class ReviewForm(forms.ModelForm):
    rank = forms.DecimalField(
        max_digits=5,
        decimal_places=1,
        max_value=5,
        min_value=0,
        label='평점',
        help_text='0~5점까지 평점을 매겨주세요.',
        widget=forms.TextInput(
            attrs={
                'placeholder': '영화 평점 입력',
                'required':'required',
                'max':'5',
                'min':'0',
            }
        )
    )
    title = forms.CharField(
        max_length=100,
        label='글 제목',
        help_text='제목은 100자이내로 작성하세요.',
        widget=forms.TextInput(
            attrs={
                'placeholder': '리뷰 제목 입력',
                'required':'required',
            }
        )
    )
    content = forms.CharField(
        label='내용',
        help_text='자유롭게 작성해주세요.',
        widget=forms.Textarea(
            attrs={
                'rows': 5,
                'cols': 50,
            }
        )
    )
    class Meta:
        model = Review
        fields = ['title', 'rank', 'content']

class CommentForm(forms.ModelForm):
    content = forms.CharField(
        label="",
        widget=forms.Textarea(
            attrs={
                'rows': 1,
                'cols': 50,
                'placeholder':'자유롭게 작성해주세요.'
            }
        )
    )
    class Meta:
        model = Comment
        fields = ['content']

project/django_pjt4/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

from .models import Movie, Review, Comment
from .forms import ReviewForm, CommentForm

def movie_index(request):
    movies = Movie.objects.all()
    context = {
        'movies':movies,
    }
    return render(request, 'articles/movie_list.html', context)

def reviews_index(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    context = {
        'movie':movie,
    }
    return render(request, 'articles/review_list.html', context)

def review_detail(request, movie_pk, review_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    review = get_object_or_404(Review, pk=review_pk)
    form = CommentForm()
    context = {
        'movie':movie,
        'review':review,
        'form':form,
    }
    return render(request, 'articles/review_detail.html', context)

@login_required
def create(request, movie_pk):
    movie=get_object_or_404(Movie, pk=movie_pk)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.hitcount=0
            review.user = request.user
            review.movie_id=movie_pk
            review.save()
            messages.info(request, '글이 작성되었습니다.')
            return redirect('articles:review_detail', movie.pk, review.pk)
    else:
        form = ReviewForm()
    context = {
        'movie':movie,
        'form':form,
    }
    return render(request, 'articles/form.html', context)

@login_required
def update(request, movie_pk, review_pk):
    movie = get_object_or_404(Movie, id=movie_pk)
    review = get_object_or_404(Review, id=review_pk)
    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            review=form.save()
            review.movie_id=movie_pk
            messages.info(request, '글이 수정되었습니다.')
            return redirect('articles:review_detail', movie.pk, review.id)
    else:
        form = ReviewForm(instance=review)
    context = {
        'form': form,
        'review':review,
        'movie':movie,
    }
    return render(request,'articles/form.html', context)

@login_required
def delete(request, movie_pk, review_pk):
    User = get_user_model()
    if request.user == get_object_or_404(User, id=get_object_or_404(Review, id=review_pk).user_id):
        review = get_object_or_404(Review, id=review_pk)
        review.delete()
        messages.info(request, '글이 삭제되었습니다.')
    return redirect('articles:reviews_index', movie_pk)



@require_POST
@login_required
def c_comment(request, movie_pk, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment.save()
        messages.info(request, '댓글이 작성되었습니다.')
    return redirect('articles:review_detail',movie_pk, review_pk)

@login_required
def d_comment(request, movie_pk, review_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    comment.delete()
    messages.info(request, '댓글이 삭제되었습니다.')
    return redirect('articles:review_detail', movie_pk, review_pk)

@login_required
def like(request, movie_pk, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if review.like_users.filter(id=request.user.pk).exists():
        review.like_users.remove(request.user)
    else:
        review.like_users.add(request.user)
    return redirect('articles:review_detail', movie_pk, review_pk)

project/django_pjt4/articles/templates/articles/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}리뷰 작성{% endblock %}
{% block content %}
    {% if request.resolver_match.url_name == 'update' %}
        <h1>EDIT</h1>
        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-primary" type="submit">수정</button><br>
            <a class="btn btn-secondary" href="{% url 'articles:review_detail' movie.pk review.pk %}">BACK</a>
        </form>
    {% else %}
        <h1>NEW</h1>
        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-primary" type="submit">작성</button><br>
            <a class="btn btn-secondary" href="{% url 'articles:reviews_index' movie.pk %}">BACK</a>
        </form>
    {% endif %}
{% endblock %}

project/django_pjt4/articles/templates/articles/movie_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}영화 목록{% endblock %}
{% block content %}
<h1>Movies</h1>
<hr>
{% for movie in movies %}
<div class="card" style="width: 18rem;">
  <img src="{{ movie.movie_poster }}" class="card-img-top" alt="movie poster">
  <div class="card-body">
    <h5 class="card-title">{{ movie.movie_title }}</h5>
    <a href="{% url 'articles:reviews_index' movie.pk %}" class="btn btn-primary">Reviews</a>
  </div>
</div>
{% endfor %}
{% endblock %}

project/django_pjt4/articles/templates/articles/review_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}리뷰{% endblock %}
{% block content %}
<h1>DETAIL</h1>
<hr>
<p>영화제목: {{ movie.movie_title }}</p>
<p>제목: {{ review.title }}</p>
<p>내용: {{ review.content }}</p>
<p>수정시각: {{ review.updated_at }}</p>
{% if request.user == review.user %}
<a class="btn btn-primary" href="{% url 'articles:update' movie.pk review.pk %}">EDIT</a>
<a class="btn btn-danger" href="{% url 'articles:delete' movie.pk review.pk %}">DELETE</a>
{% endif %}
<br>
<a class="btn btn-secondary" href="{% url 'articles:reviews_index' movie.pk%}">BACK</a>
<hr>
    {% with review_like_users=review.like_users.all %}
        {% if request.user in review_like_users %}
        <a href="{% url 'articles:like' movie.pk review.pk %}">
            <i class="fas fa-heart fa-lg animated delay-1s" style="color: red;"></i>
        </a>
        {% else %}
        <a href="{% url 'articles:like' movie.pk review.pk %}">
            <i class="far fa-heart fa-lg animated infinite bounce delay-1s" style="color: gray;"></i>
        </a>
        {% endif %}
        <p>{{ review_like_users|length }}명이 좋아합니다.</p>
    {% endwith %}
<hr>
<form action="{% url 'articles:c_comment' movie.pk review.pk %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-primary">작성</button>
</form>
<hr>
{% for comment in review.comments.all reversed %}
    <p class="d-inline">{{ forloop.revcounter }} : {{ comment.content }}{% if request.user == comment.user %}<form class="d-inline" action="{% url 'articles:d_comment' movie.pk review.pk comment.pk %}" method="post">{% csrf_token %}<button class="btn btn-danger">삭제</button></form>{% endif %}</p>
    <hr>
{% empty%}
	<p>관심과 사랑이 필요합니다 ㅠㅠ 첫번쨰 댓글을 달아주세요</p>
{% endfor %}
{% endblock %}

project/django_pjt4/articles/templates/articles/review_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}리뷰 목록{% endblock %}
{% block content %}
<h1>Reviews</h1>
<hr>
<a class="btn btn-primary" href="{% url 'articles:create' movie.pk %}">글쓰기</a>
<hr>
<div class="container">
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col">#</th>
        <th scope="col">영화</th>
        <th scope="col">평점</th>
        <th scope="col">제목</th>
        <th scope="col">조회수</th>
        <th scope="col">좋아요</th>
        <th scope="col">작성자</th>
        <th scope="col">작성 시간</th>
      </tr>
    </thead>
    <tbody>
     {% for review in movie.reviews.all reversed%}
      <tr>
        <td scope="row">{{ forloop.counter }}</td>
        <td scope="row">{{ movie.movie_title }}</td>
        <td scope="row"><span class="badge badge-warning">{{ review.rank }}</span></td>
        <td scope="row"><a class="btn btn-info" href="{% url 'articles:review_detail' movie.pk review.pk %}">{{ review.title }}</a></td>
        <td scope="row">{{ review.hitcount }}</td>
        <td scope="row">{{ review.like_users.count }}</td>
        <td scope="row"><a class="btn btn-info" href="{% url 'accounts:profile' review.user.username %}">{{ review.user.username }}</a></td>
        <td scope="row">{{ review.created_at }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}