project/django_pjt3/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
]

project/django_pjt3/community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('',views.read, name='index'),
    path('create/',views.create, name='create'),
    path('<int:review_pk>/',views.detail, name='detail'),
    path('<int:review_pk>/update/',views.update, name='update'),
    path('<int:review_pk>/delete/',views.delete, name='delete'),
    path('<int:review_pk>/comments/',views.c_create, name='c_create'),
    path('<int:review_pk>/comments/<int:comment_pk>/delete',views.c_delete, name='c_delete'),
]

project/django_pjt3/django_pjt3/urls.py
from django.contrib import admin
from django.urls import path, include
from community import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.read),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
]

project/django_pjt3/accounts/models.py
from django.db import models

# Create your models here.

project/django_pjt3/community/models.py
from django.db import models
from django.conf import settings


# Create your models here.

class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    title = models.CharField(max_length = 100)
    movie_title = models.CharField(max_length = 30)
    rank = models.IntegerField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    hitcount = models.IntegerField()

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    review = models.ForeignKey(Review,on_delete=models.CASCADE)
    content = models.CharField(max_length = 200)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

project/django_pjt3/community/forms.py
from django import forms
from .models import Review, Comment

class ReviewForm(forms.ModelForm):
    movie_title = forms.CharField(
        max_length=30,
        label='영화 제목',
        help_text='영화 제목은 30자로 제한됩니다.',
        widget=forms.TextInput(
            attrs={
                'placeholder': '영화 제목 입력',
                'required':'required',
                'autofocus':'autofocus',
            }
        )
    )
    rank = forms.DecimalField(
        max_digits=5,
        decimal_places=1,
        max_value=5,
        min_value=0,
        label='평점',
        help_text='0~5점까지 평점을 매겨주세요.',
        widget=forms.TextInput(
            attrs={
                'placeholder': '영화 평점 입력',
                'required':'required',
                'max':'5',
                'min':'0',
            }
        )
    )
    title = forms.CharField(
        max_length=100,
        label='글 제목',
        help_text='제목은 100자이내로 작성하세요.',
        widget=forms.TextInput(
            attrs={
                'placeholder': '리뷰 제목 입력',
                'required':'required',
            }
        )
    )
    content = forms.CharField(
        label='내용',
        help_text='자유롭게 작성해주세요.',
        widget=forms.Textarea(
            attrs={
                'rows': 5,
                'cols': 50,
            }
        )
    )
    class Meta:
        model = Review
        fields = ['title', 'movie_title', 'rank', 'content']

class CommentForm(forms.ModelForm):
    content = forms.CharField(
        label="",
        widget=forms.Textarea(
            attrs={
                'rows': 1,
                'cols': 50,
                'placeholder':'자유롭게 작성해주세요.'
            }
        )
    )
    class Meta:
        model = Comment
        fields = ['content']

project/django_pjt3/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.contrib import messages

@login_required
def delete(request):
    request.user.delete()
    messages.info(request, '회원탈퇴 되었습니다.')
    return redirect('community:index')

def signup(request):
    if request.user.is_authenticated:
        return redirect('community:index')

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, '회원가입 되었습니다.')
            return redirect('community:index')
    else:
        form = UserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('community:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            messages.info(request, '로그인 되었습니다.')
            return redirect(request.GET.get('next') or 'community:index')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form
    }
    return render(request, 'accounts/login.html', context)

@login_required
def logout(request):
    auth_logout(request)
    messages.info(request, '로그아웃 되었습니다.')
    return redirect('community:index')

project/django_pjt3/community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

from .models import Review, Comment
from .forms import ReviewForm, CommentForm

# Create your views here.
def read(request):
    reviews = Review.objects.order_by('-pk')
    context = {
        'reviews':reviews,
    }
    return render(request, 'community/review_list.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.hitcount=0
            review.user = request.user
            review.save()
            messages.info(request, '글이 작성되었습니다.')
            return redirect('community:detail', review.pk)
    else:
        form = ReviewForm()
    context = {
        'form':form,
    }
    return render(request, 'community/form.html', context)

def detail(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    review.hitcount+=1
    review.save()
    form = CommentForm()
    context = {
        'review':review,
        'form':form,
    }
    return render(request, 'community/review_detail.html', context)

@require_POST
@login_required
def c_create(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment.save()
        messages.info(request, '댓글이 작성되었습니다.')
    return redirect('community:detail',review.pk)

@login_required
def c_delete(request,review_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    comment.delete()
    messages.info(request, '댓글이 삭제되었습니다.')
    return redirect('community:detail', review_pk)

@login_required
def update(request, review_pk):
    review = get_object_or_404(Review, id=review_pk)
    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            review=form.save()
            messages.info(request, '글이 수정되었습니다.')
            return redirect('community:detail', review.id)
    else:
        form = ReviewForm(instance=review)
    context = {
        'form': form,
        'review':review,
    }
    return render(request,'community/form.html', context)

@require_POST
def delete(request, review_pk):
    if request.user == get_object_or_404(User, id=rget_object_or_404(Review, id=review_pk).user_id):
        review = get_object_or_404(Review, id=review_pk)
        review.delete()
        messages.info(request, '글이 삭제되었습니다.')
    return redirect('community:index')

project/django_pjt3/community/templates/community/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}글 작성{% endblock %}
{% block content %}
    {% if request.resolver_match.url_name == 'update' %}
        <h1>EDIT</h1>
        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-primary" type="submit">수정</button><br>
            <a class="btn btn-secondary" href="{% url 'community:detail' review.pk %}">BACK</a>
        </form>
    {% else %}
        <h1>NEW</h1>
        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-primary" type="submit">작성</button><br>
            <a class="btn btn-secondary" href="{% url 'community:index' %}">BACK</a>
        </form>
    {% endif %}
{% endblock %}

project/django_pjt3/community/templates/community/review_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}글 세부내용{% endblock %}
{% block content %}
<h1>DETAIL</h1>
<hr>
<p>제목: {{ review.title }}</p>
<p>내용: {{ review.content }}</p>
<p>생성시각: {{ review.created_at }}</p>
<p>수정시각: {{ review.updated_at }}</p>
{% if request.user == review.user %}
<a class="btn btn-primary" href="{% url 'community:update' review.pk %}">EDIT</a>
<a class="btn btn-danger" href="{% url 'community:delete' review.pk %}">DELETE</a>
{% endif %}
<br>
<a class="btn btn-secondary" href="{% url 'community:index' %}">BACK</a>
<hr>
<form class="d-flex" action="{% url 'community:c_create' review.pk %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-primary">작성</button>
</form>
<hr>
{% for comment in review.comment_set.all reversed %}
    <p class="d-inline">{{ forloop.revcounter }} : {{ comment.content }}{% if request.user == comment.user %}<form class="d-inline" action="{% url 'community:c_delete' review.id comment.id %}" method="post">{% csrf_token %}<button class="btn btn-danger">삭제</button></form>{% endif %}</p>
    <hr>
{% empty%}
	<p>관심과 사랑이 필요합니다 ㅠㅠ 첫번쨰 댓글을 달아주세요</p>
{% endfor %}

{% endblock %}

project/django_pjt3/community/templates/community/review_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}글 목록{% endblock %}
{% block content %}
<h1>Reviews</h1>
<hr>
<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
        <!--<img src="/static/img/.png" class="d-block w-100" alt="...">-->
    </div>
    </div>
  </div>
</div>
<div class="container">
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col">#</th>
        <th scope="col">영화</th>
        <th scope="col">평점</th>
        <th scope="col">제목</th>
        <th scope="col">조회수</th>
        <th scope="col">작성자</th>
        <th scope="col">작성 시간</th>
      </tr>
    </thead>
    <tbody>
     {% for review in reviews %}
      <tr>
        <td scope="row">{{ review.pk }}</td>
        <td scope="row">{{ review.movie_title }}</td>
        <td scope="row"><span class="badge badge-warning">{{ review.rank }}</span></td>
        <td scope="row"><a class="btn btn-info" href="{% url 'community:detail' review.id %}">{{ review.title }}</a></td>
        <td scope="row">{{ review.hitcount }}</td>
        <td scope="row">{{ review.user.username }}</td>
        <td scope="row">{{ review.created_at }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}