0427/either/either/urls.py
from django.contrib import admin
from django.urls import path, include
from issue import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('issue/', include('issue.urls')),
]

0427/either/issue/urls.py
from django.urls import path, include
from issue import views

app_name='issue'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:issue_pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:issue_pk>/reply/', views.reply, name='reply'),
    path('random/', views.random, name='random'),
]

0427/either/issue/models.py
from django.db import models

# Create your models here.
class Issue(models.Model):
    nameA = models.CharField(max_length = 20)
    nameB = models.CharField(max_length = 20)
    hitcountA = models.IntegerField()
    hitcountB = models.IntegerField()

class Reply(models.Model):
    issue = models.ForeignKey(Issue, on_delete=models.CASCADE)
    pick = models.CharField(max_length = 2)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add = True)

0427/either/issue/forms.py
from django import forms
from .models import Issue, Reply

class IssueForm(forms.ModelForm):
    nameA = forms.CharField(
        max_length=20,
        label='',
        help_text='20자로 제한됩니다.',
        widget=forms.TextInput(
            attrs={
                'placeholder': '비교대상 1 입력',
                'required':'required',
                'autofocus':'autofocus',
            }
        )
    )
    nameB = forms.CharField(
        max_length=20,
        label='',
        help_text='20자로 제한됩니다.',
        widget=forms.TextInput(
            attrs={
                'placeholder': '비교대상 2 입력',
                'required':'required',
            }
        )
    )
    class Meta:
        model = Issue
        fields = ['nameA','nameB']


CHOICES=[('A','A'),('B','B')]
class ReplyForm(forms.ModelForm):
    pick = forms.ChoiceField(
        label='',
        choices=CHOICES,
        widget=forms.RadioSelect(
            attrs={
                'class':"radio-inline"
            }
        )
    )
    comment = forms.CharField(
        label='',
        widget=forms.TextInput(
            attrs={
                'placeholder':'자유롭게 작성해주세요.'
            }
        )
    )
    class Meta:
        model = Reply
        fields = ['pick','comment']

0427/either/issue/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views.decorators.http import require_POST

from .models import Issue, Reply
from .forms import IssueForm, ReplyForm

def index(request):
    issues = Issue.objects.order_by('-pk')
    context = {
        'issues':issues,
    }
    return render(request, 'issue/index.html', context)

def detail(request, issue_pk):
    issue = get_object_or_404(Issue, pk=issue_pk)
    form = ReplyForm()
    context = {
        'issue':issue,
        'form':form,
    }
    return render(request, 'issue/detail.html', context)

def create(request):
    if request.method == 'POST':
        form = IssueForm(request.POST)
        if form.is_valid():
            issue = form.save(commit=False)
            issue.hitcountA=0
            issue.hitcountB=0
            issue.save()
            messages.info(request, '이슈가 작성되었습니다.')
            return redirect('issue:detail', issue.pk)
    else:
        form = IssueForm()
    context = {
        'form':form,
    }
    return render(request, 'issue/form.html', context)

def reply(request,issue_pk):
    issue = get_object_or_404(Issue, pk=issue_pk)
    form = ReplyForm(request.POST)
    if form.is_valid():
        reply = form.save(commit=False)
        if reply.pick=='A':
            issue.hitcountA+=1
        else:
            issue.hitcountB+=1
        issue.save()
        reply.issue = issue
        reply.save()
        messages.info(request, '의견이 반영되었습니다.')
    return redirect('issue:detail', issue.pk)

def random(request):
    issues=Issue.objects.all()
    import random
    issue=random.choice(issues)
    return redirect('issue:detail',issue.pk)

0427/either/templates/_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Sehoon Either</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item d-flex">
        <a class="nav-link" href="{% url 'issue:random' %}">Random Issue</a>
        <a class="nav-link" href="{% url 'issue:create' %}">New Issue</a>
      </li>
    </ul>
  </div>
</nav>

0427/either/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <header class="sticky-top">
      {% include '_nav.html'%}
    </header>
    {% if messages %}
    	{% for message in messages %}
    		<div class="alert alert-info text-center w-100" role="alert">
    		{{ message.message }}
        </div>
    	{% endfor %}
    {% endif %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
<script src="/static/js/jquery-3.4.1.min.js" type="text/javascript"></script>
<script src="/static/js/popper-1.16.0.min.js" type="text/javascript"></script>
<script src="/static/js/bootstrap.min.js" type="text/javascript"></script>
</html>